### ISSUE TITLE
Access to DDC pretrained weights in Google Drive

### ISSUE THREAD

**Issue by YuQiao0303** [Hanyu-Chen373/DeepDataConsistency#1]
Hi authors, thank you for this amazing work! 

I'm trying to run the code, but when trying downloading the pretrained weights, Google Drive says that "You need access". May you please check this out? Thank you!!!
![image](https://github.com/Hanyu-Chen373/DeepDataConsistency/assets/28769198/78bc2e80-58fd-4b03-a969-1c276aa4d0ca)

**Comment by Hanyu-Chen373** [comment]
Thank you very much for pointing out the problem!
We incorrectly set up the share link earlier, and it should now be available for everyone to download.

**Comment by YuQiao0303** [comment]
> Thank you very much for pointing out the problem! We incorrectly set up the share link earlier, and it should now be available for everyone to download.

Thank you! Now it can be downloaded and used.
